export const culturalCenters = [
  {
    id: 1,
    name: "Centro Cultural Metropolitano",
    description: "Exposición de arte contemporáneo con obras de artistas locales e internacionales.",
    date: "15 - 30 Enero",
    time: "10:00 - 18:00",
    image: "/placeholder.svg?height=400&width=400",
    category: "Arte",
  },
  {
    id: 2,
    name: "Teatro Nacional",
    description: "Presentación de la obra clásica 'Romeo y Julieta' con el elenco nacional.",
    date: "20 - 25 Enero",
    time: "19:30 - 21:30",
    image: "/placeholder.svg?height=400&width=400",
    category: "Teatro",
  },
  {
    id: 3,
    name: "Museo de Historia",
    description: "Nueva exhibición sobre la historia precolombina y sus tradiciones ancestrales.",
    date: "1 - 28 Febrero",
    time: "09:00 - 17:00",
    image: "/placeholder.svg?height=400&width=400",
    category: "Historia",
  },
  {
    id: 4,
    name: "Centro de Música",
    description: "Concierto de música clásica con la orquesta sinfónica de la ciudad.",
    date: "10 - 12 Febrero",
    time: "20:00 - 22:00",
    image: "/placeholder.svg?height=400&width=400",
    category: "Música",
  },
  {
    id: 5,
    name: "Galería de Arte Moderno",
    description: "Retrospectiva de pintores del siglo XX con más de 100 obras en exhibición.",
    date: "5 - 20 Marzo",
    time: "11:00 - 19:00",
    image: "/placeholder.svg?height=400&width=400",
    category: "Arte Moderno",
  },
]; 